name: {{.Name}}
version: {{.Version}}
source:
{{- range $key, $value := .Source }}
  type: {{$key}}
  config: {{$value | indent 4}}
{{- end }}
{{- if ne (len .Sinks) 0 }}
sinks:
{{- range $key, $value := .Sinks }}
  - name: {{$key}}
    {{- if  $value}}
    config: {{$value | indent 6}}
    {{- end }}    
{{- end }}
{{- end }}
{{- if ne (len .Processors) 0 }}
processors:
{{- range $key, $value := .Processors }}
  - name: {{$key}}
    {{- if  $value}}
    config: {{$value | indent 6}}
    {{- end }}
{{- end }}
{{- end }}
