# nindent
name: {{.Name}}
source:
{{- range $key, $value := .Source }}
  type: {{$key}}
  config: {{$value | nindent 4}}
{{- end }}
{{- if ne (len .Sinks) 0 }}
sinks:
{{- range $key, $value := .Sinks }}
  - name: {{$key}}
    {{- if  $value}}
    config: {{$value | nindent 6}}
    {{- end }}    
{{- end }}
{{- end }}
{{- if ne (len .Processors) 0 }}
processors:
{{- range $key, $value := .Processors }}
  - name: {{$key}}
    {{- if  $value}}
    config: {{$value | nindent 6}}
    {{- end }}
{{- end }}
{{- end }}
