version: '3'
services:
  mongo:
    image: mongo:4.4.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=abcd
    restart: on-failure
    ports:
      - 27017:27017
  mysql:
    image: mysql:8.0.25
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - '3306:3306'
    expose:
      - '3306'
