name: Build Dev

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2.6.1
      with:
        distribution: goreleaser
        version: latest
        args: --snapshot --rm-dist
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Tag dev image
      run: docker tag docker.io/odpf/meteor:latest docker.io/odpf/meteor:dev
    - name: Push Images
      run: docker push docker.io/odpf/meteor:dev
