name: Build
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get release tag
      id: get_version
      uses: battila7/get-version-action@v2
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
            docker.pkg.github.com/${{ github.repository }}/meteor:latest
            docker.pkg.github.com/${{ github.repository }}/meteor:${{ steps.get_version.outputs.version-without-v }}
            odpf/meteor:latest
            odpf/meteor:${{ steps.get_version.outputs.version-without-v }}
