name: Plugins Test

on:
  push:
    branches:
      - main
      - fix-plugin-tests
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install dependencies
        run: sudo apt-get install build-essential
      - name: Install packages
        run: go mod tidy
      - name: Run Test
        run: make test-plugins
