name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.4.6
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: user
          MONGO_INITDB_ROOT_PASSWORD: abcd
      mysql:
        image: mysql:8.0.25
        ports:
          - '3306:3306'
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
      postgres:
        image: postgres:13.3
        ports:
          - 5432:5432
        env:
          - POSTGRES_USER: root
          - POSTGRES_PASSWORD: pass
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install dependencies
        run: sudo apt-get install build-essential
      - name: Install packages
        run: go mod tidy
      - name: Run Test
        run: make test
